/** Copyright 2022 Google LLC
* 
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* https://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

// This file is a hardcoded version of the [official codes file](https://developers.google.com/authorized-buyers/rtb/downloads/creative-status-codes).

namespace CreativeStatusCodes {
    export const mapping: { [key: number]: string } = {
        1: "Creative won the auction",
        2: "Internal error",
        3: "Unknown error (deprecated)",
        4: "Internal error: unknown status code",
        5: "Creative filtered due to landing page quality",
        6: "Creative filtered because malware was detected",
        7: "Creative URL has not yet been reviewed",
        8: "Unknown error (deprecated)",
        9: "Unknown error (deprecated)",
        10: "Creative was not approved",
        11: "Creative has not yet been categorized",
        12: "Creative filtered by publisher through the Publisher Controls ad review tool",
        13: "Creative filtered because the context of the inventory was incompatible with ad content, according to ad policy",
        14: "Creative filtered because of detected excluded_sensitive_category",
        15: "Creative filtered because one or more detected product categories were excluded in the bid request",
        16: "Creative filtered because one or more detected vendors are ineligible to serve ads on the Ad Exchange",
        17: "Creative filtered because one or more declared vendors were excluded in the bid request",
        18: "Creative filtered because one or more declared attributes were excluded in the bid request",
        19: "Creative filtered because one or more declared sensitive categories were excluded in the bid request",
        20: "Unknown error (deprecated)",
        21: "Creative filtered because the required field buyer_creative_id is missing",
        22: "Creative filtered because no matching ad slot was found",
        23: "Creative filtered because the returned adgroup_id is invalid (not one of the matched adgroups)",
        24: "Creative filtered because the required adgroup_id field is missing",
        25: "Creative filtered because the declared width and height do not match the request",
        26: "Creative filtered because the required fields width or height are missing",
        27: "Creative filtered because it includes more than one of the following: html_snippet, video_url",
        28: "Creative filtered because click_through_url was not empty",
        29: "Unknown error (deprecated)",
        30: "Unknown error (deprecated)",
        31: "Unknown error (deprecated)",
        32: "Unknown error (deprecated)",
        33: "Creative filtered because the required field html_snippet was empty",
        34: "Creative filtered because the required field video_url was empty",
        35: "Unknown error (deprecated)",
        36: "Creative filtered because the required field click_through_url was empty",
        37: "Creative filtered because html_snippet should be empty when video is requested",
        38: "Creative filtered because video_url field was not empty, should be empty unless video is requested",
        39: "Unknown error (deprecated)",
        40: "Unknown error (deprecated)",
        41: "Unknown error (deprecated)",
        42: "Unknown error (deprecated)",
        43: "Unknown error (deprecated)",
        44: "Unknown error (deprecated)",
        45: "Unknown error (deprecated)",
        46: "Unknown error (deprecated)",
        47: "Unknown error (deprecated)",
        48: "Unknown error (deprecated)",
        49: "Unknown error (deprecated)",
        50: "Unknown error (deprecated)",
        51: "Unknown error (deprecated)",
        52: "Unknown error (deprecated)",
        53: "Unknown error (deprecated)",
        54: "Unknown error (deprecated)",
        55: "Unknown error (deprecated)",
        56: "Creative filtered because the field click_through_url is too short, must be at least 11 characters",
        57: "Creative filtered because the field click_through_url could not be parsed",
        58: "Creative filtered because the field click_through_url has a domain consisting of all digits",
        59: "Creative filtered because the field video_url is too short, must be at least 11 characters",
        60: "Creative filtered because the field video_url could not be parsed",
        61: "Creative filtered because the field video_url has a domain consisting of all digits",
        62: "Unknown error (deprecated)",
        63: "Creative filtered because an expandable vendor was declared, but expandable directions are missing from Ad.attribute",
        64: "Creative filtered because expandable directions were passed in Ad.attribute, but an expandable vendor declaration is missing",
        65: "Unknown error (deprecated)",
        66: "Creative filtered because the field buyer_creative_id exceeds 64 bytes",
        67: "Creative filtered because max_cpm_micros is not greater than or equal to min_cpm_micros",
        68: "Creative filtered because max_cpm_micros is not greater than 0",
        69: "Unknown error (deprecated)",
        70: "Unknown error (deprecated)",
        71: "Creative filtered due to publisher's URL exclusion settings",
        72: "Creative filtered due to publisher's advertiser exclusion settings",
        73: "Creative filtered due to publisher's targeting type settings",
        74: "Creative filtered because it has historically had a high error rate and/or very low view rate",
        75: "Creative filtered because the hosted creative had the wrong size or was not in a matching adgroup",
        76: "Creative filtered because the VAST XML contains errors or could not be fetched for verification",
        77: "Creative is awaiting review by the publisher",
        78: "Creative filtered because the declared creative size was not present in pre-targeting adgroup",
        79: "Creative was outbid",
        80: "Creative filtered because the bid price was below the minimum CPM threshold",
        81: "Creative was not allowed in Private Auction or Preferred Deal",
        82: "Creative filtered because the ad language is not allowed by the publisher",
        83: "The ad was part of a winning passback chain and will only show if preceding requests in the chain pass back",
        84: "Creative filtered because the publisher disallows ads from this agency",
        85: "Creative requires additional review",
        86: "Creative filtered because one or more undeclared restricted_category fields were detected",
        87: "Creative filtered because one or more declared restricted_category fields do not match the request",
        88: "Creative filtered because deal_id is not for a valid deal",
        89: "Interstitial ad size declared is either too big or too small to show on the device screen (it needs to cover at least 50% of screen width and 40% height)",
        90: "AdX VAST ad type does not match the type required in the video ad request",
        91: "Creative filtered because the duration of the video is too long",
        92: "Creative filtered because the duration of the video is too short",
        93: "Creative filtered because it is a skippable video ad for a non-skippable request",
        94: "Creative filtered because it is a non-skippable video ad for a skippable-only request",
        95: "Creative filtered because the skip offset is wrong (5 seconds is the correct value)",
        96: "Creative filtered because it lacks a MP4 video file in the VAST",
        97: "Creative filtered because it lacks a WebM video file in the VAST",
        98: "Creative filtered because it lacks a Flash video file in the VAST",
        99: "Creative filtered because it lacks a required video MIME type in the VAST file (the specific missing type is not available)",
        100: "Unknown error (deprecated)",
        101: "Unknown error (deprecated)",
        102: "Creative filtered because the bidder account is in testing mode",
        103: "Native ad specified for an adslot that does not support it",
        104: "native_ad.image.url field value is an invalid URL",
        105: "native_ad.logo.url field value is an invalid URL",
        106: "native_ad.app_icon.url field value is an invalid URL",
        107: "Required elements specified in bid_request.adslot.native_ad_template.required_fields are missing or empty",
        108: "Unknown error (deprecated)",
        109: "Unknown error (deprecated)",
        110: "Unknown error (deprecated)",
        111: "native_ad.click_tracking_url field value is too short to be a valid URL",
        112: "native_ad.click_tracking_url field value cannot be parsed as a valid URL",
        113: "native_ad.click_tracking_url field value has a domain that is all digits",
        114: "Creative filtered because deal_id is invalid",
        115: "ADX_AD_SOURCE_TYPE_MANAGED_TAG does not support deals",
        116: "Creative filtered because deal's buyer_network_id is invalid",
        117: "Creative filtered because deal's advertiser is invalid",
        118: "Creative filtered because a deal id is required",
        119: "Creative filtered by publisher's exclusion rules",
        120: "Creative filtered because the language could not be detected and the publisher has language restrictions",
        121: "Creative filtered because the billing entity it is attributed to is out of budget",
        122: "Creative filtered due to frequency caps",
        123: "Creative filtered because it is not allowed to serve on the Android platform",
        124: "Creative filtered because it is not allowed to serve on the iOS platform",
        125: "impression_tracking_url field value is too short to be a valid URL",
        126: "impression_tracking_url field value cannot be parsed as a valid URL",
        127: "impression_tracking_url field value has a domain that is all digits",
        128: "impression_tracking_url not supported for non mobile-app html ads",
        129: "Creative filtered because it is ineligible or unapproved for serving to a Chinese user or property",
        130: "Creative filtered because it is ineligible or unapproved for serving to a Russian user or property",
        131: "Creative has not yet been reviewed or is not currently active, and the account has too many active snippets.  Please contact your technical account manager",
        132: "native_ad.image.width or native_ad.image.height has an invalid value",
        133: "native_ad.logo.width or native_ad.logo.height has an invalid value",
        134: "native_ad.app_icon.width or native_ad.app_icon.height has an invalid value",
        135: "native_ad.store field value is an invalid URL",
        136: "native_ad.star_rating field value is invalid",
        137: "Creative filtered because ad.width/height is not allowed for the chosen deal",
        138: "Creative filtered because max_cpm_micros is too large",
        139: "Creative filtered because bidder used an unsupported OpenRTB feature",
        140: "Unknown error (deprecated)",
        141: "Exactly one adslot was expected for the ad; either zero or multiple were returned",
        142: "Creative is not SSL compliant but secure ads are required on this request",
        143: "Creative uses flash but flash is not available or not allowed on this request",
        144: "Creative filtered by publisher's creative text filter rules",
        145: "The adslot ID specified in the response did not match any in the request",
        146: "The creative was not eligible to serve to the current user",
        147: "Unknown error (deprecated)",
        148: "Unknown error (deprecated)",
        149: "The click tracking URL is too short to be a valid URL",
        150: "The click tracking URL cannot be parsed as valid URL",
        151: "The click tracking URL has a domain that is all digits",
        152: "Invalid ad.adslot.billing_id in the bid response",
        153: "ad.adslot.billing_id in the bid response does not match any adslot.matching_ad_data.billing_id in the bid request",
        154: "Creative filtered because buyer_creative_id is not UTF8 compliant",
        155: "ad_choices_destination_url field value is too short to be a valid URL",
        156: "ad_choices_destination_url field value  cannot be parsed as a valid URL",
        157: "ad_choices_destination_url field value has a domain that is all digits",
        158: "Ad rejected because it is an HTML ad that plays video, and the impression excludes video ads",
        159: "native_ad.video_url field value is an invalid URL",
        160: "native_ad.click_link_url field value is an invalid URL",
        161: "Creative filtered because it lacks a VPAID Flash file in the VAST",
        162: "Creative filtered because it lacks a VPAID JavaScript file in the VAST",
        163: "Native ad image asset width not in permitted range",
        164: "Native ad image asset aspect ratio not in permitted range",
        165: "Creative filtered by publisher's restrictions on which brands can be shown together",
        166: "Deal bid filtered because the publisher didn't enable deals for the exchange.",
        167: "Publisher requires premium (high-quality) snippets only, but this snippet does not match",
        168: "Creative filtered because it lacks a MP3 (audio) file in the VAST",
        169: "Creative filtered because it lacks a AUDIO (audio) file in the VAST",
        170: "Creative filtered because it lacks a MOV file in the VAST",
        171: "Creative filtered because it lacks a 3GPP file in the VAST",
        172: "Creative filtered because it lacks a DASH file in the VAST",
        173: "Creative filtered because it lacks an HLS file in the VAST",
        174: "Creative filtered because it lacks an MP4A file in the VAST",
        175: "Creative filtered because it has an empty VAST XML document.",
        176: "Creative filtered because the VAST document can't be parsed.",
        177: "Creative filtered because request requires assets to have a bitrate within a specified range",
        178: "Creative filtered because request requires assets to have a resolution within a specified range",
        179: "Creative filtered because the required field amp_ad_url was missing or empty.",
        180: "Video ad VAST version is not one of the supported versions in the video ad request",
        181: "Creative filtered because the VAST XML document is larger than the set maximum size.",
        182: "Creative filtered beacuse the publisher blocklisted the deal ID it targeted",
        183: "Creative filtered beacuse the publisher enabled the deal ID it targeted for a different deal type",
        184: "Creative filtered because the field amp_ad_url is too short, must be at least 11 characters",
        185: "Creative filtered because the field amp_ad_url could not be parsed",
        186: "Creative filtered because the field amp_ad_url has a domain consisting of all digits",
        187: "Creative filtered because of creative policy violations",
        188: "Creative filtered due to publisher's app exclusion settings",
        189: "Filtered due to unknown SDK identifier",
        190: "Filtered due to disallowed SDK identifier",
        191: "Creative filtered because it contains an invalid OMSDK script URL.",
        192: "Rejected due to Coppa/KFA being filtered for demand syndication.",
        193: "Filtered due to missing SDK identifier",
        194: "Filtered due to missing SDK rendering data",
        195: "Creative lost to a Private Auction, Preferred Deal, or Programmatic Guaranteed Deal.",
        196: "The publisher has blocked the buyer for this bid.",
        197: "The response did not comply with demand syndication guidelines",
        198: "The publisher has blocked all open auction bids (which does not include Private Auction, Preferred Deals, or Programmatic Guaranteed Deals) on the request.",
        199: "Filtered due to experimental changes",
        200: "iOS requests disallow video ads missing the playsinline attribute",
        201: "The TC string doesn't contain consent for one of the vendors included in this ad creative.",
        202: "Ad contains an invalid IAB GVL macro, for instance a consent macro with a GVL ID anything other than a positive integer",
        203: "Ad contains a GDPR consent macro with a GVL ID not present in the latest version of the Global Vendor List",
        204: "The creative's instream format is not allowed (i.e. linear vs. non-linear)",
        205: "Creative was disapproved",
        206: "Ad filtered because it does not match the format of the chosen deal",
        207: "Ad filtered because publisher does not support the iOS SKAdNetwork API",
        208: "Ad filtered because the provided iOS SKAdNetwork version does not match the publisher's version",
        209: "Ad filtered because the provided iOS SKAdNetwork publisher app ID does not match the publisher's app ID",
        210: "Ad filtered because the provided iOS SKAdNetwork ad network ID does not match one of the publisher's supported network IDs in the app's Info.plist",
        211: "Ad filtered because the provided iOS SKAdNetwork is missing required fields",
        212: "The ad is filtered because the bid is for a PG deal with publisher-managed creatives and contains bidder-provided creative information.",
        213: "A provided ad load notification URL is too short to be a valid URL.",
        214: "A provided ad load notification URL cannot be parsed as a valid URL.",
        215: "A provided ad load notification URL has a domain that is all digits.",
        216: "Ad load notification URLs are not supported for non mobile-app SDK rendered ads.",
        217: "Click tracking URLs are supported only for native ads or PG deals with publisher-hosted creatives and rejected otherwise.",
        218: "Ad contains a vendor domain that could not be attributed to any known vendor.",
        219: "The list of ad technology providers used by the publisher to collect consent doesn't contain one of the vendors included in this ad creative.",
        220: "Native ad filtered because it contains both video URL and VAST tag.",
        221: "Native ad filtered because the VAST XML document is empty.",
        222: "Native ad filtered because the VAST XML document is too large.",
        223: "Bid filtered due to malformed frequency caps or because frequency capping was specified for a request which doesn't support it.",
        224: "Multiple bids submitted for a single deal ID on a bid response.",
        225: "Ad filtered because the provided iOS SKAdNetwork fidelity type is not supported by the ad query.",
        226: "Ad filtered because the provided currency on the OpenRTB bid response is different from the bidding currency.",
        227: "Ad filtered because it has been detected to contain at least one sensitive category that is disallowed on Multiplex ad slot.",
        228: "Ad rejected because bidder specified an unexpected billing ID when bidding on a deal.",
        229: "Ad rejected because billable event rate adjustment computed from bid and payment doesn't match adjustment sent in bid request.",
        230: "A provided ad load notification URL exceeded the maximum length.",
        231: "Ad rejected because the vast lacks an MP4A media file and the request requires an ad with an MP4A media file.",
        232: "Ad rejected because the device screen orientation is landscape (width > height) but no single media asset of the returned video ad is in landscape.",
        233: "Ad rejected because the publisher blocked non-instream video in protections.",
        234: "Ad rejected because the publisher blocked display ads in protections.",
        235: "Ad filtered because the currency specified in the bid response is invalid."
    }
}